-- Habilitar la extensión para UUID si aún no está activa
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Creación de la tabla 'courses'
CREATE TABLE courses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    color VARCHAR(50) NOT NULL DEFAULT '#3b82f6',
    default_duration INTEGER NOT NULL DEFAULT 120,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Creación de la tabla 'professors'
CREATE TABLE professors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Creación de la tabla 'schedules'
CREATE TABLE schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id UUID NOT NULL,
    professor_id UUID NOT NULL,
    room VARCHAR(100) NOT NULL,
    start_time VARCHAR(5) NOT NULL, -- Formato "HH:mm"
    end_time VARCHAR(5) NOT NULL,   -- Formato "HH:mm"
    day_of_week INTEGER NOT NULL,   -- 0 a 6
    section VARCHAR(100),
    module INTEGER,                -- Almacenado como entero (ej. 1, 2, 3)
    session VARCHAR(10),           -- Almacenado como texto/varchar para soportar el formato con ceros a la izquierda, ej. "09", "11"
    schedule_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Restricciones de clave foránea con eliminación en cascada
    CONSTRAINT fk_course FOREIGN KEY (course_id) 
        REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_professor FOREIGN KEY (professor_id) 
        REFERENCES professors(id) ON DELETE CASCADE
);

-- Creación de índices para mejorar el rendimiento de las consultas
CREATE INDEX idx_schedules_course_id ON schedules(course_id);
CREATE INDEX idx_schedules_professor_id ON schedules(professor_id);
CREATE INDEX idx_schedules_day_and_time ON schedules(day_of_week, start_time, end_time);

-- Ejecuta esto en el SQL Editor de Supabase
ALTER TABLE professors DISABLE ROW LEVEL SECURITY;
ALTER TABLE courses DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedules DISABLE ROW LEVEL SECURITY;

-- Crear tabla de perfiles en el esquema público
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  full_name TEXT,
  role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'viewer'))
);

-- Habilitar RLS (Seguridad a nivel de fila)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- Políticas de acceso
CREATE POLICY "Usuarios pueden ver su propio perfil" 
  ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Usuarios pueden actualizar su propio perfil" 
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

  -- Función para auto-crear perfil al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger de automatización
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

  -- enablesecuritytry26

  -- Crear tabla de salones
CREATE TABLE public.rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  building TEXT,
  capacity INTEGER,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
-- Insertar salones iniciales (opcional, basados en tu código previo)
INSERT INTO public.rooms (name) VALUES ('201'), ('202'), ('301'), ('401'), ('402'), ('Multiuso');
-- Habilitar RLS (Seguridad)
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
-- Políticas de acceso
CREATE POLICY "Permitir lectura a todos" ON public.rooms FOR SELECT USING (true);
CREATE POLICY "Permitir todo a usuarios autenticados" ON public.rooms FOR ALL USING (auth.role() = 'authenticated');

-- 1. Eliminar la columna antigua de texto
ALTER TABLE schedules DROP COLUMN IF EXISTS room;

-- 2. Agregar la nueva columna de relación (Llave Foránea)
-- Nota: Usa 'BIGINT' si tus IDs de salones son números o 'UUID' si son texto largo.
ALTER TABLE schedules ADD COLUMN room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL;